### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by sirikid**
I rewrote most of the tests using `assertThat`

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your suggested pull request. I will comment directly in the individual commits

**Comment by lukaseder** [comment]
Thanks again for your suggestions.

I understand that some things might not please you, and there is always a better way to express code from a stylistic point of view. However, the risk of regressions in accepting a pull request this large for almost no real benefit is too high. This is why I'm rejecting it (except for the two typo fixes).

Thanks for your understanding.

**Comment by sirikid** [comment]
It's okay, I'm just experimenting with bitwise operations and rewrote tests in passing.

**Comment by lukaseder** [comment]
Oh, interesting. What kind of operations were you thinking of?

**Comment by sirikid** [comment]
The original purpose to rewrite ULong without using BigInteger to store the value.

**Comment by lukaseder** [comment]
Oh, that would be really interesting, indeed!

**Comment by sirikid** [comment]
[Here](https://gist.github.com/sirikid/9b40277ac7e2bb300463) is sketch, tests passes, and old and new.

**Comment by lukaseder** [comment]
Oh, I see. But this seems to be using Java 8... I'd like to postpone that upgrade in the dependency for as long as possible...

**Comment by sirikid** [comment]
It's simple, pure functions without dependencies, I think won't be a great sin if I just copy them.

**Comment by lukaseder** [comment]
The last time someone copied `ArrayList.rangeCheck()` from Oracle, they were sued beyond a couple of billions...

**Pull request closed without merging**
